/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/neutral/neutralTheme.ts
 * Command: astryx theme build src/themes/neutral/neutralTheme.ts
 * Generated: 2026-07-21T17:09:30.326Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
