/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/neutral/neutralTheme.ts
 * Command: astryx theme build src/themes/neutral/neutralTheme.ts
 * Generated: 2026-07-21T17:09:30.328Z
 */

/// <reference path="./neutral.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
